services:
  db:
    image: ankane/pgvector:pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-torob}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-torob}
      POSTGRES_DB: ${POSTGRES_DB:-torob}
    ports:
      - "${PG_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - torob-db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://torob:torob@db:5432/torob}
      TOROB_BOOTSTRAP: ${TOROB_BOOTSTRAP:-0}
      TOROB_DATA_DIR: /data/torob
      REPLAY_LOG_DIR: /var/log/assistant/replay
      TOROB_AUTO_EMBED: ${TOROB_AUTO_EMBED:-0}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - torob-data:/data/torob
      - replay-logs:/var/log/assistant/replay
    command: ["/app/start.sh"]

volumes:
  torob-db:
  torob-data:
  replay-logs:
