[project]
name = "ttlr-final-challenge"
version = "0.1.0"
description = "Shopping assistant prototype built around Pydantic-AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.28",
    "pydantic-ai>=0.0.10",
    "polars>=0.20",
    "psycopg>=3.1",
    "adbc-driver-postgresql>=1.1",
    "gdown>=5.2.0",
]
